CREATE TABLE CLIENTE(
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100)
);

CREATE TABLE PRODUTO(
    ID INTEGER NOT NULL  PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(100),
    PRECO_UNITARIO NUMERIC(20,2)
);

CREATE TABLE PEDIDO(
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INTEGER NOT NULL,
    DATA_PEDIDO TIMESTAMP,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE
);

CREATE TABLE ITEM_PEDIDO(
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INTEGER NOT NULL,
    ID_PRODUTO INTEGER NOT NULL,
    QUANTIDADE INTEGER,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE,
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO
);